spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mywebstack
    username: root
    password: 123456
  security:
    jwt:
      key: abcdefghijk
      expire: 7

  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.example: debug
